//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fractalz.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fractalz.Application.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш пин-код:.
        /// </summary>
        internal static string MessageEmailRecource {
            get {
                return ResourceManager.GetString("MessageEmailRecource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможно нарушена связь с сервером.
        /// </summary>
        internal static string ServerFailed {
            get {
                return ResourceManager.GetString("ServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша почта не подтверждена.
        /// </summary>
        internal static string User_codeValidWron {
            get {
                return ResourceManager.GetString("User_codeValidWron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email уже используется в системе.
        /// </summary>
        internal static string User_emailExist {
            get {
                return ResourceManager.GetString("User_emailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email не существует.
        /// </summary>
        internal static string User_emailNotExist {
            get {
                return ResourceManager.GetString("User_emailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email содержит недопустимые символы.
        /// </summary>
        internal static string User_emailSpecialSymbolValidationFalse {
            get {
                return ResourceManager.GetString("User_emailSpecialSymbolValidationFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес почты не содержит требуемых условий.
        /// </summary>
        internal static string User_emailValidation_At_Sign_False {
            get {
                return ResourceManager.GetString("User_emailValidation\"At_Sign\"False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой логин уже зарегистрирован.
        /// </summary>
        internal static string User_loginExist {
            get {
                return ResourceManager.GetString("User_loginExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный логин, введите другой логин или Email.
        /// </summary>
        internal static string User_loginWron {
            get {
                return ResourceManager.GetString("User_loginWron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотябы одну заглавную букву.
        /// </summary>
        internal static string User_passwordIsUpperCharValidationFalse {
            get {
                return ResourceManager.GetString("User_passwordIsUpperCharValidationFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть меньше 18 символов.
        /// </summary>
        internal static string User_passwordMaxLenghtValidationFalse {
            get {
                return ResourceManager.GetString("User_passwordMaxLenghtValidationFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть больше 6 символов.
        /// </summary>
        internal static string User_passwordMinLenghtValidationFalse {
            get {
                return ResourceManager.GetString("User_passwordMinLenghtValidationFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен содержать хотябы одну прописную букву.
        /// </summary>
        internal static string User_passwordRegularSymbolsValidationFalse {
            get {
                return ResourceManager.GetString("User_passwordRegularSymbolsValidationFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не верный пароль, введите другой пароль или попробуйте восстановить его.
        /// </summary>
        internal static string User_passwordWron {
            get {
                return ResourceManager.GetString("User_passwordWron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно обновить пользовательский статус.
        /// </summary>
        internal static string User_UpdatestatusError {
            get {
                return ResourceManager.GetString("User_UpdatestatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не существует.
        /// </summary>
        internal static string UserUndefind {
            get {
                return ResourceManager.GetString("UserUndefind", resourceCulture);
            }
        }
    }
}
